version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - type: volume
        source: postgres
        target: /pgdata
    hostname: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    volumes:
      - type: volume
        source: pgadmin4
        target: /var/lib/pgadmin
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
volumes:
  postgres:
  pgadmin4:
